add ping, set, unset

diff --git a/clashctl b/clashctl
--- a/clashctl
+++ b/clashctl
@@ -77,6 +77,9 @@ show_usage() {
   echo "start                         start clash"
   echo "stop                          stop clash"
   echo "reload                        reload clash"
+  echo "set                           set proxy"
+  echo "unset                         unset proxy"
+  echo "ping                          curl google.com"
   echo "update <url>                  download config from <url> and reload clash"
   echo "proxies                       show proxy information"
   echo "switch <proxy> [selector]     switch proxy to <proxy> in [selector], default selector is Proxies"
@@ -88,32 +91,20 @@ start() {
   echo "[INFO] stopping potential clash running behind"
   rmLog
   stop
-  echo "[INFO] starting http(s) proxy at $proxy_endpoint"
-  export http_proxy=$proxy_endpoint
-  export https_proxy=$proxy_endpoint
+  set_
 
   echo "[INFO] using clash $clash"
   nohup $clash -d $config > $nohup_out 2>&1 &
 
   sleep 2
-  curl -s --connect-timeout 2 google.com > /dev/null
-  if [[ $? != 0 ]]
-  then
-    echo "[ERROR] $icon_error failed to start clash."
-    stop
-  else
-    echo -e "[INFO] $icon_success clash started."
-  fi
+  ping
 }
 
 
 stop() {
   pkill -2 clash
   echo "[INFO] stopped clash."
-
-  unset http_proxy
-  unset https_proxy
-  echo "[INFO] stopped http(s) proxy."
+  unset_
 }
 
 
@@ -128,6 +119,31 @@ reload() {
   stop
   sleep 2
   start
+}
+
+
+set_() {
+  echo "[INFO] starting http(s) proxy at $proxy_endpoint"
+  export http_proxy=$proxy_endpoint
+  export https_proxy=$proxy_endpoint
+}
+
+
+unset_() {
+  unset http_proxy
+  unset https_proxy
+  echo "[INFO] stopped http(s) proxy."
+}
+
+
+ping() {
+  curl -s --connect-timeout 2 google.com > /dev/null
+  if [[ $? != 0 ]]
+  then
+    echo "[ERROR] $icon_error falied to connect to google."
+  else
+    echo -e "[INFO] $icon_success google is now available."
+  fi
 }
 
 
@@ -191,6 +207,21 @@ main() {
   then
     echo "[INFO] reloading..."
     reload
+
+  elif [[ $1 == "set" ]]
+  then
+    echo "[INFO] setting proxy..."
+    set_
+
+  elif [[ $1 == "unset" ]]
+  then
+    echo "[INFO] unsetting proxy..."
+    unset_
+
+  elif [[ $1 == "ping" ]]
+  then
+    echo "[INFO] checking connection..."
+    ping
 
   elif [[ $1 == "update" ]]
   then
